### <font> https://www.youtube.com/watch?v=RlQuVL6-qe8&t=1050s </font>
###  <font color=red>Loading the data </font>

In [22]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()           # It is better to read it in Pandas
X = iris.data                         # X = iris_data
y = iris.target                       # y = iris_labels
print(X[0], iris_data[79], X[100])
print(y[0], y[79], y[100])

[5.1 3.5 1.4 0.2] [5.7 2.6 3.5 1. ] [6.3 3.3 6.  2.5]
0 1 2


In [23]:
print(X.shape)

(150, 4)


In [24]:
print(y.shape)

(150,)


###  <font color=red > Selecting the proper modeling class  </font>

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [18]:
knn.fit(X, y)
knn.predict([[3, 5, 4, 2]])

array([2])

In [19]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

### <font color=red> Using a different value for K </font>

In [20]:
# instantiate the model (using the value K=5)
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model with data
knn.fit(X, y)

# predict the response for new observations
knn.predict(X_new)

array([1, 1])

### <font color=red> Using a different classification model </font>

In [21]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X, y)

# predict the response for new observations
logreg.predict(X_new)

array([2, 0])